//! The Promptly fitness function, ported to Rust with parity to `13` (`19`).
//!
//! `promptly score` must produce the same number the web HUD (`11`) projects and
//! the server (`12`) persists. To guarantee that with no re-typed numbers, this
//! module embeds the shared `13`/`19` fixture generated by `lib/scoring`
//! (`lib/scoring/parity-fixture.json`): the canonical scoring constants, the
//! per-`challenge_type` token weights, the full `model_economics` matrix (the
//! CLI's offline economics), and the independently-verified scoring vectors. The
//! formula below mirrors `lib/scoring/score.ts` operation-for-operation, and the
//! parity test drives the embedded vectors through it — so CI fails if either
//! side diverges (`13a`).
//!
//! Master equation (`13`):
//! ```text
//! Score = (C * W_c / (P * M_effort))
//!       * (1e3 / (T_in*W_in + T_out*W_out + T_think*W_think))
//!       * (100 / (S * W_s))
//! ```
//! with the documented anti-degeneracy floors (`13a`): `P >= 1`, `S >= 1.0s`,
//! weighted tokens `>= 100`, and `M_effort` clamped to `[0.50, 3.00]`.

use std::collections::HashMap;
use std::sync::OnceLock;

use serde::Deserialize;

/// The generated scoring fixture, embedded at build time from `vendor/`. It is
/// mirrored from the Promptly web app's `lib/scoring/parity-fixture.json`; the
/// parity test (`scores_match_the_shared_parity_vectors`) pins this Rust port to
/// it so the two scoring implementations can never silently diverge.
const PARITY_FIXTURE_JSON: &str = include_str!("../../../vendor/parity-fixture.json");

/// The `harness_used` value that triggers the Cursor Composer modifier (`13a`).
const CURSOR_COMPOSER_HARNESS: &str = "cursor";

/// Canonical scoring constants, mirrored from `13a` via the shared fixture.
#[derive(Debug, Clone, Deserialize)]
pub struct ScoringConstants {
    pub w_c: f64,
    pub w_s: f64,
    pub p_min: f64,
    pub s_floor: f64,
    pub t_floor: f64,
    pub thinking_overhead_step_tokens: f64,
    pub thinking_overhead_per_step: f64,
    pub thinking_overhead_max: f64,
    pub score_token_scale: f64,
    pub score_speed_scale: f64,
    pub m_effort_min: f64,
    pub m_effort_max: f64,
    pub composer_modifier: f64,
    /// Effort-base floor applied when the capture's token counts are adapter
    /// ESTIMATES rather than harness-reported usage (the server's 2026-07-15
    /// fairness rule): an unverifiable capture's model id can't buy a sub-anchor
    /// divisor. The current fixture predates the constant, so it defaults to the
    /// value of `ESTIMATED_COUNTS_EFFORT_FLOOR` in `lib/scoring/constants.ts`.
    #[serde(default = "default_estimated_counts_effort_floor")]
    pub estimated_counts_effort_floor: f64,
}

fn default_estimated_counts_effort_floor() -> f64 {
    1.0
}

/// Per-`challenge_type` token weights `{ W_in, W_out, W_think }`.
#[derive(Debug, Clone, Copy, Deserialize)]
pub struct TokenWeights {
    pub w_in: f64,
    pub w_out: f64,
    pub w_think: f64,
}

/// One `model_economics` row. Extra fields in the fixture (lab, notes, thinking
/// cost, anchor flag) are ignored — only what scoring needs is read here.
#[derive(Debug, Clone, Deserialize)]
pub struct EconomicsRow {
    pub model_identifier: String,
    #[serde(default)]
    pub input_cost: Option<f64>,
    #[serde(default)]
    pub output_cost: Option<f64>,
    pub base_effort_multiplier: f64,
    #[serde(default)]
    pub is_baseline_floor: bool,
}

// The scoring vectors are only consumed by the parity test; in a release build
// serde simply ignores the fixture's `vectors` key, so the binary carries no
// unused deserialization.
#[cfg(test)]
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
struct VectorTokens {
    input: f64,
    output: f64,
    thinking: f64,
}

#[cfg(test)]
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
struct VectorInput {
    correctness_pct: f64,
    prompt_count: f64,
    tokens: VectorTokens,
    execution_time_seconds: f64,
    challenge_type: String,
    model_identifier: String,
    harness_used: String,
}

#[cfg(test)]
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ParityVector {
    name: String,
    input: VectorInput,
    expected_score: f64,
    expected_effort: f64,
    expected_baseline_floor: bool,
}

#[derive(Debug, Clone, Deserialize)]
struct Fixture {
    constants: ScoringConstants,
    token_weights: HashMap<String, TokenWeights>,
    economics: Vec<EconomicsRow>,
    #[cfg(test)]
    vectors: Vec<ParityVector>,
}

fn fixture() -> &'static Fixture {
    static FIXTURE: OnceLock<Fixture> = OnceLock::new();
    FIXTURE.get_or_init(|| {
        serde_json::from_str(PARITY_FIXTURE_JSON)
            .expect("embedded parity-fixture.json is generated by lib/scoring and always valid")
    })
}

/// The canonical scoring constants.
pub fn constants() -> &'static ScoringConstants {
    &fixture().constants
}

/// The offline `model_economics` matrix (the CLI's economics reference, `13`).
pub fn economics() -> &'static [EconomicsRow] {
    &fixture().economics
}

/// How a model id resolved to an economics row.
pub struct ResolvedEconomics {
    pub row: &'static EconomicsRow,
    /// True when the requested model was unknown/marker and the floor was used.
    pub baseline_floor_fallback: bool,
}

/// Canonicalize a raw model id to the matrix's spelling — the Rust mirror of the
/// web's `lib/scoring/model-id.ts`, implemented byte-for-byte so a local score /
/// watch prices a harness-reported id the same way server grading does. A real
/// run reports a datestamped id (`claude-haiku-4-5-20251001`); without this it
/// would miss its priced row and floor.
///
/// The contract:
/// (a) lowercase;
/// (b) replace every RUN of characters not in `[a-z0-9]` with a single `-`;
/// (c) trim leading/trailing `-`;
/// (d) if the result ends with `-20\d{6}` (dash + exactly 8 digits starting `20`),
///     strip that ONE trailing segment.
///
/// No month/day validation (`-20123456` still counts as a datestamp); an 8-digit
/// segment not starting `20` (`-12345678`) is kept; no provider-prefix or `@tag`
/// handling. Simple char scanning, no regex dependency.
pub fn canonicalize_model_id(raw: &str) -> String {
    // (a) + (b): lowercase alphanumerics pass through; every other run collapses
    // to a single `-` (checking `is_ascii_alphanumeric` before lowercasing is
    // equivalent — ASCII letters lowercase in place, everything else is a `-`).
    let mut out = String::with_capacity(raw.len());
    let mut prev_dash = false;
    for ch in raw.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
            prev_dash = false;
        } else if !prev_dash {
            out.push('-');
            prev_dash = true;
        }
    }
    // (c): trim the leading/trailing separators.
    let trimmed = out.trim_matches('-');
    // (d): drop one trailing `-20\d{6}` datestamp segment. The segment is the run
    // after the last `-`; requiring exactly 8 digits starting `20` matches the
    // anchored regex without validating the date.
    if let Some(idx) = trimmed.rfind('-') {
        let tail = &trimmed[idx + 1..];
        if tail.len() == 8 && tail.starts_with("20") && tail.bytes().all(|b| b.is_ascii_digit()) {
            return trimmed[..idx].to_string();
        }
    }
    trimmed.to_string()
}

/// Pick the economics row to score `model_identifier` against. A recognized
/// priced model uses its own row — matched on the raw id first, then on its
/// [`canonicalize_model_id`] form (so a datestamped harness id resolves) — while
/// an unknown model, or a marker row with null prices (e.g. `cursor-composer`),
/// falls back to the baseline-floor tier, the exact behavior of
/// `resolveModelEconomics` (`13`).
pub fn resolve_economics(model_identifier: &str) -> ResolvedEconomics {
    let matrix = economics();
    let find_priced = |id: &str| -> Option<&'static EconomicsRow> {
        matrix
            .iter()
            .find(|r| r.model_identifier == id && r.input_cost.is_some() && r.output_cost.is_some())
    };
    let row = find_priced(model_identifier).or_else(|| {
        let canonical = canonicalize_model_id(model_identifier);
        // Skip the redundant rescan when canonicalization changed nothing.
        (canonical != model_identifier)
            .then(|| find_priced(&canonical))
            .flatten()
    });
    if let Some(row) = row {
        return ResolvedEconomics {
            row,
            baseline_floor_fallback: false,
        };
    }
    let floor = matrix
        .iter()
        .find(|r| r.is_baseline_floor)
        .expect("model_economics fixture always carries a baseline-floor row");
    ResolvedEconomics {
        row: floor,
        baseline_floor_fallback: true,
    }
}

/// Resolve token weights for a challenge type, applying usable per-level
/// overrides over the `13a` defaults (mirrors `resolveTokenWeights`). Override
/// keys are `W_in`/`W_out`/`W_think` (the manifest's `token_weight_overrides`).
pub fn resolve_token_weights(
    challenge_type: &str,
    overrides: Option<&HashMap<String, f64>>,
) -> TokenWeights {
    let table = &fixture().token_weights;
    let base = table
        .get(challenge_type)
        .or_else(|| table.get("implementation"))
        .copied()
        .expect("token-weight defaults always include the balanced tier");
    let usable = |key: &str| {
        overrides
            .and_then(|o| o.get(key))
            .copied()
            .filter(|v| v.is_finite() && *v >= 0.0)
    };
    TokenWeights {
        w_in: usable("W_in").unwrap_or(base.w_in),
        w_out: usable("W_out").unwrap_or(base.w_out),
        w_think: usable("W_think").unwrap_or(base.w_think),
    }
}

/// Token counts for an attempt (summed across turns).
#[derive(Debug, Clone, Copy)]
pub struct Tokens {
    pub input: f64,
    pub output: f64,
    pub thinking: f64,
}

/// Everything the fitness function needs. Mirrors `ScoreSubmissionInput` (`13`):
/// a concrete `model_identifier` resolved upstream, not a pre-resolved row.
#[derive(Debug, Clone)]
pub struct ScoreInput {
    pub correctness_pct: f64,
    pub prompt_count: f64,
    pub tokens: Tokens,
    pub execution_time_seconds: f64,
    pub challenge_type: String,
    pub model_identifier: String,
    pub harness_used: String,
    /// True when the token counts are adapter estimates (any `estimated`-
    /// confidence turn taints the capture) — floors the effort base at anchor
    /// parity, mirroring `computeEffort`'s `countsEstimated` (`13`).
    pub counts_estimated: bool,
}

/// The itemized `M_effort` derivation (mirrors `EffortBreakdown`, `13`).
#[derive(Debug, Clone)]
pub struct EffortBreakdown {
    pub model_identifier: String,
    pub base: f64,
    /// True when estimated counts floored `base` above the model's own
    /// multiplier (mirrors `baseFloored` in the web breakdown).
    pub base_floored: bool,
    pub thinking_overhead: f64,
    pub composer_modifier: f64,
    pub raw: f64,
    pub value: f64,
    pub is_baseline_floor: bool,
    pub clamped: bool,
}

/// Every factor of the equation, for a transparent breakdown (mirrors `13`).
#[derive(Debug, Clone)]
pub struct ScoreBreakdown {
    pub correctness_value: f64,
    pub prompts_effective: f64,
    pub prompts_floored: bool,
    pub effort: EffortBreakdown,
    pub weights: TokenWeights,
    pub tokens: Tokens,
    pub weighted_tokens: f64,
    pub effective_weighted: f64,
    pub tokens_floored: bool,
    pub token_value: f64,
    pub seconds_effective: f64,
    pub speed_floored: bool,
    pub speed_value: f64,
}

/// The fitness score, its breakdown, and how the model resolved.
#[derive(Debug, Clone)]
pub struct ScoreResult {
    pub score: f64,
    pub breakdown: ScoreBreakdown,
    /// True when the model id fell back to the baseline-floor tier (unrecognized).
    pub baseline_floor_fallback: bool,
}

/// Coerce to a finite, non-negative value (NaN / −∞ / negative → 0), matching
/// `nonNegative` in `score.ts`.
fn non_negative(value: f64) -> f64 {
    if value.is_finite() && value > 0.0 {
        value
    } else {
        0.0
    }
}

/// `min(1.00, 0.05 × floor(total_thinking / 5000))` (`13a`).
pub fn thinking_overhead(total_thinking_tokens: f64) -> f64 {
    let c = constants();
    let tokens = if total_thinking_tokens.is_finite() {
        total_thinking_tokens.max(0.0)
    } else {
        0.0
    };
    let steps = (tokens / c.thinking_overhead_step_tokens).floor();
    (c.thinking_overhead_per_step * steps).min(c.thinking_overhead_max)
}

/// Clamp `M_effort` into the canonical `[0.50, 3.00]` band (`13a`).
fn clamp_multiplier(value: f64) -> f64 {
    let c = constants();
    value.max(c.m_effort_min).min(c.m_effort_max)
}

/// Resolve a model id against the matrix, then score — the single entry point
/// (mirrors `scoreSubmission`, `13`). Pure: same inputs → same output.
pub fn score_submission(
    input: &ScoreInput,
    overrides: Option<&HashMap<String, f64>>,
) -> ScoreResult {
    let c = constants();
    let resolved = resolve_economics(&input.model_identifier);
    let weights = resolve_token_weights(&input.challenge_type, overrides);

    // Effort uses the RAW thinking tokens (its own non-negative guard inside).
    // Estimated-count captures floor the base at anchor parity (`computeEffort`).
    let model_base = resolved.row.base_effort_multiplier;
    let base = if input.counts_estimated {
        model_base.max(c.estimated_counts_effort_floor)
    } else {
        model_base
    };
    let overhead = thinking_overhead(input.tokens.thinking);
    let composer = if input.harness_used == CURSOR_COMPOSER_HARNESS {
        c.composer_modifier
    } else {
        0.0
    };
    let raw_effort = base + overhead + composer;
    let effort = clamp_multiplier(raw_effort);

    let correctness_pct = non_negative(input.correctness_pct);
    let correctness_value = correctness_pct * c.w_c;

    let raw_prompts = non_negative(input.prompt_count);
    let prompts_effective = raw_prompts.max(c.p_min);

    let tokens = Tokens {
        input: non_negative(input.tokens.input),
        output: non_negative(input.tokens.output),
        thinking: non_negative(input.tokens.thinking),
    };
    let weighted = tokens.input * weights.w_in
        + tokens.output * weights.w_out
        + tokens.thinking * weights.w_think;
    let effective_weighted = weighted.max(c.t_floor);

    let raw_seconds = non_negative(input.execution_time_seconds);
    let seconds_effective = raw_seconds.max(c.s_floor);

    // Same operation order as `score.ts`, so the f64 result is bit-identical.
    let correctness_factor = correctness_value / (prompts_effective * effort);
    let token_value = c.score_token_scale / effective_weighted;
    let speed_value = c.score_speed_scale / (seconds_effective * c.w_s);
    let score = correctness_factor * token_value * speed_value;

    ScoreResult {
        score,
        baseline_floor_fallback: resolved.baseline_floor_fallback,
        breakdown: ScoreBreakdown {
            correctness_value,
            prompts_effective,
            prompts_floored: prompts_effective > raw_prompts,
            effort: EffortBreakdown {
                model_identifier: resolved.row.model_identifier.clone(),
                base,
                base_floored: base != model_base,
                thinking_overhead: overhead,
                composer_modifier: composer,
                raw: raw_effort,
                value: effort,
                is_baseline_floor: resolved.row.is_baseline_floor,
                clamped: raw_effort < c.m_effort_min || raw_effort > c.m_effort_max,
            },
            weights,
            tokens,
            weighted_tokens: weighted,
            effective_weighted,
            tokens_floored: effective_weighted > weighted,
            token_value,
            seconds_effective,
            speed_floored: seconds_effective > raw_seconds,
            speed_value,
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Close-enough for cross-language f64 parity (the ops are identical-order,
    /// so this is generous — it catches real divergence, not sub-ULP noise).
    fn approx(a: f64, b: f64) -> bool {
        (a - b).abs() / b.abs().max(1.0) < 1e-9
    }

    #[test]
    fn matrix_invariants_hold() {
        let m = economics();
        assert!(
            m.iter().any(|r| r.is_baseline_floor),
            "a baseline-floor row exists"
        );
        let anchor = m
            .iter()
            .find(|r| r.model_identifier == "claude-sonnet-4-6")
            .expect("anchor row present");
        assert!(
            (anchor.base_effort_multiplier - 1.0).abs() < 1e-12,
            "anchor is 1.00"
        );
        assert!(!fixture().vectors.is_empty(), "parity vectors present");
    }

    #[test]
    fn scores_match_the_shared_13_parity_vectors() {
        // The single source of truth for "the same inputs" — generated from `13`'s
        // own constants/matrix/vectors, so equality here IS local/server parity.
        for v in &fixture().vectors {
            let input = ScoreInput {
                correctness_pct: v.input.correctness_pct,
                prompt_count: v.input.prompt_count,
                tokens: Tokens {
                    input: v.input.tokens.input,
                    output: v.input.tokens.output,
                    thinking: v.input.tokens.thinking,
                },
                execution_time_seconds: v.input.execution_time_seconds,
                challenge_type: v.input.challenge_type.clone(),
                model_identifier: v.input.model_identifier.clone(),
                harness_used: v.input.harness_used.clone(),
                // Every shared vector is a measured-counts capture (the fixture
                // deliberately carries no estimated vectors).
                counts_estimated: false,
            };
            let result = score_submission(&input, None);
            assert!(
                approx(result.score, v.expected_score),
                "score parity [{}]: got {}, want {}",
                v.name,
                result.score,
                v.expected_score,
            );
            assert!(
                (result.breakdown.effort.value - v.expected_effort).abs() < 1e-9,
                "M_effort parity [{}]: got {}, want {}",
                v.name,
                result.breakdown.effort.value,
                v.expected_effort,
            );
            assert_eq!(
                result.baseline_floor_fallback, v.expected_baseline_floor,
                "baseline-floor parity [{}]",
                v.name,
            );
        }
    }

    #[test]
    fn unknown_model_falls_back_to_the_floor_and_composer_keys_on_harness() {
        let floor = resolve_economics("totally-made-up-model");
        assert!(floor.baseline_floor_fallback);
        assert!(floor.row.is_baseline_floor);

        // Composer adds exactly +0.20 over the underlying model's base.
        let base = ScoreInput {
            correctness_pct: 100.0,
            prompt_count: 2.0,
            tokens: Tokens {
                input: 5000.0,
                output: 3000.0,
                thinking: 0.0,
            },
            execution_time_seconds: 4.0,
            challenge_type: "debugging".into(),
            model_identifier: "claude-sonnet-4-6".into(),
            harness_used: "claude_code_cli".into(),
            counts_estimated: false,
        };
        let plain = score_submission(&base, None);
        let mut composer = base.clone();
        composer.harness_used = "cursor".into();
        let with_composer = score_submission(&composer, None);
        assert!(
            (with_composer.breakdown.effort.value - (plain.breakdown.effort.value + 0.2)).abs()
                < 1e-12,
        );
    }

    #[test]
    fn estimated_counts_floor_the_effort_base_at_anchor_parity() {
        // A cheap model over an estimated capture pays the anchor's base — the
        // server's `countsEstimated` rule (`computeEffort`, 2026-07-15). Cursor's
        // real composer-2-5 case: base 0.50 → floored 1.00, +0.20 Composer.
        let mut input = ScoreInput {
            correctness_pct: 100.0,
            prompt_count: 1.0,
            tokens: Tokens {
                input: 500.0,
                output: 300.0,
                thinking: 0.0,
            },
            execution_time_seconds: 1.0,
            challenge_type: "debugging".into(),
            model_identifier: "composer-2-5".into(),
            harness_used: "cursor".into(),
            counts_estimated: true,
        };
        let floored = score_submission(&input, None);
        assert!(floored.breakdown.effort.base_floored);
        assert!(
            (floored.breakdown.effort.base - constants().estimated_counts_effort_floor).abs()
                < 1e-12,
            "base floored to anchor parity, got {}",
            floored.breakdown.effort.base,
        );
        assert!((floored.breakdown.effort.value - 1.2).abs() < 1e-12);

        // The same capture with measured counts keeps the model's own economics.
        input.counts_estimated = false;
        let measured = score_submission(&input, None);
        assert!(!measured.breakdown.effort.base_floored);
        assert!(
            measured.breakdown.effort.base < 1.0,
            "composer-2-5's own base is sub-anchor"
        );
        assert!(measured.score > floored.score, "the floor can only cost");

        // The floor is a max, never a discount: an expensive model is unchanged.
        input.model_identifier = "claude-opus-4-8".into();
        input.harness_used = "claude_code_cli".into();
        input.counts_estimated = true;
        let expensive = score_submission(&input, None);
        assert!(!expensive.breakdown.effort.base_floored);
        assert!(expensive.breakdown.effort.base > 1.0);
    }

    #[test]
    fn canonicalize_mirrors_the_web_model_id_contract() {
        // (d) strips one trailing `-20\d{6}` datestamp.
        assert_eq!(
            canonicalize_model_id("claude-haiku-4-5-20251001"),
            "claude-haiku-4-5"
        );
        assert_eq!(
            canonicalize_model_id("claude-opus-4-8-20260115"),
            "claude-opus-4-8"
        );
        // (a)+(b): lowercase and collapse non-alphanumeric runs (dots → `-`).
        assert_eq!(canonicalize_model_id("Claude-Opus-4.8"), "claude-opus-4-8");
        assert_eq!(canonicalize_model_id("claude opus 4.8"), "claude-opus-4-8");
        // (c): leading/trailing separators trimmed.
        assert_eq!(canonicalize_model_id("  gpt-5.5  "), "gpt-5-5");
        // Already-canonical passthrough.
        assert_eq!(canonicalize_model_id("claude-opus-4-8"), "claude-opus-4-8");
        // No month/day validation — `-20123456` still counts as a datestamp.
        assert_eq!(
            canonicalize_model_id("claude-haiku-4-5-20123456"),
            "claude-haiku-4-5"
        );
        // An 8-digit segment not starting `20` is left intact.
        assert_eq!(canonicalize_model_id("foo-12345678"), "foo-12345678");
        // A 7- or 9-digit trailing run is not a datestamp.
        assert_eq!(canonicalize_model_id("foo-2025100"), "foo-2025100");
        assert_eq!(canonicalize_model_id("foo-202510012"), "foo-202510012");
        // Idempotent: canonicalizing the canonical form is a no-op.
        let once = canonicalize_model_id("claude-haiku-4-5-20251001");
        assert_eq!(canonicalize_model_id(&once), once);
    }

    #[test]
    fn resolve_economics_prices_datestamped_and_dotted_ids() {
        // A datestamped known id resolves to its real priced row (haiku's own
        // base multiplier), not the baseline floor.
        let haiku = resolve_economics("claude-haiku-4-5-20251001");
        assert!(!haiku.baseline_floor_fallback);
        assert_eq!(haiku.row.model_identifier, "claude-haiku-4-5");
        assert!((haiku.row.base_effort_multiplier - 0.5).abs() < 1e-12);
        assert!(!haiku.row.is_baseline_floor);

        // A dotted spelling canonicalizes onto the opus row.
        let opus = resolve_economics("claude-opus-4.8");
        assert!(!opus.baseline_floor_fallback);
        assert_eq!(opus.row.model_identifier, "claude-opus-4-8");

        // An already-canonical id still matches on the raw pass.
        let sonnet = resolve_economics("claude-sonnet-4-6");
        assert!(!sonnet.baseline_floor_fallback);
        assert_eq!(sonnet.row.model_identifier, "claude-sonnet-4-6");

        // An unknown datestamped id still floors after canonicalization.
        let unknown = resolve_economics("gpt-4o-mini-20240718");
        assert!(unknown.baseline_floor_fallback);
        assert!(unknown.row.is_baseline_floor);
    }

    #[test]
    fn token_weight_overrides_win_when_usable() {
        let mut overrides = HashMap::new();
        overrides.insert("W_in".to_string(), 2.0);
        let weights = resolve_token_weights("debugging", Some(&overrides));
        assert!((weights.w_in - 2.0).abs() < 1e-12, "usable override wins");
        assert!(
            (weights.w_out - 0.6).abs() < 1e-12,
            "untouched default kept"
        );

        // A negative override is ignored in favour of the default.
        overrides.insert("W_out".to_string(), -1.0);
        let weights = resolve_token_weights("debugging", Some(&overrides));
        assert!(
            (weights.w_out - 0.6).abs() < 1e-12,
            "negative override ignored"
        );
    }
}
